"Name: \PR:SAPMF02K\FO:LEAVE_TO_TRANSACTION\SE:BEGIN\EI
ENHANCEMENT 0 ZEHPROXY_PROVEEDORES.

    "04.08.2015 JLGF 4172 - Se Cambio a User Exit ZXF05U01
    IF SY-TCODE EQ 'FK01' OR SY-TCODE EQ 'XK01'
    OR SY-TCODE EQ 'FK02' OR SY-TCODE EQ 'FK03' "JDDTS 8060 19.05.2020 Se agregan mas TX
    OR SY-TCODE EQ 'FK04' OR SY-TCODE EQ 'FK05'
    OR SY-TCODE EQ 'FK06' OR SY-TCODE EQ 'XK02'.

      IF SY-MSGID = 'F2'
    AND LFA1-LIFNR IS NOT INITIAL " 04.08.2015 JPM
    AND ( SY-MSGNO = '056' OR SY-MSGNO = '170' OR SY-MSGNO = '172'
     OR SY-MSGNO = '170' OR SY-MSGNO = '173' OR SY-MSGNO = '175' OR SY-MSGNO = '271' ).
*        CALL FUNCTION 'ZMF_PROXY_PROVEEDORES'
*        EXPORTING
*          LIFNR         = LFA1-LIFNR.
        BREAK: ISMARAMIREZ.
        "***IRM 15.02.2017 Req. 5390
        CALL FUNCTION 'ZMF_CREATE_JOB_PROV'
          EXPORTING
            V_LIFNR = LFA1-LIFNR.
       ENDIF.
    ENDIF.

ENDENHANCEMENT.
