"Name: \IC:MM06EF0E_EKPO-ELIKZ\EX:MM06EF0E_EKPO-ELIKZ_02\EI
ENHANCEMENT 0 ZENH_MEMASSPO3.
    IF SY-CPROG EQ 'MASSBACK' OR SY-TCODE EQ 'MASS'. "OR SY-CPROG EQ 'ZUTI_MM_CIERRE_DE_PEDIDOS' OR SY-TCODE EQ 'ZU001'. "JDDTS 03.04.2018
      EXIT.
    ENDIF.
ENDENHANCEMENT.
