"Name: \FU:CLA1_CREATE_CLFMAS\SE:END\EI
ENHANCEMENT 0 ZENH_CLFMAS_OV10_C5.
*    DATA: WA_MVKE LIKE MVKE.
*    SELECT SINGLE * INTO WA_MVKE FROM MVKE WHERE MATNR EQ object
*    AND VKORG EQ 'OV10'
*    AND VTWEG EQ 'C5'
*    AND KTGRM EQ '01'.
*    IF SY-SUBRC NE 0.
*      REFRESH   t_idoc_data.
*      CLEAR t_idoc_data.
*      EXIT.
*    ENDIF.

ENDENHANCEMENT.
