"Name: \FU:MASTER_IDOC_DISTRIBUTE\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_DELETE_SEGMENTS.
     DATA: WA2_EDP13 LIKE EDP13.

    SELECT SINGLE * FROM EDP13 INTO WA2_EDP13
    WHERE RCVPRN = MASTER_IDOC_CONTROL-RCVPRN
    AND   RCVPRT = MASTER_IDOC_CONTROL-RCVPRT
    AND   RCVPFC = MASTER_IDOC_CONTROL-RCVPFC
    AND   MESTYP = MASTER_IDOC_CONTROL-MESTYP
    AND   MESCOD = MASTER_IDOC_CONTROL-MESCOD
    AND   MESFCT = MASTER_IDOC_CONTROL-MESFCT
    AND   TEST   = MASTER_IDOC_CONTROL-TEST.

    IF WA2_EDP13-IDOCTYP NE 'ZSORTLST_WBBDLD05'.
        LOOP AT MASTER_IDOC_DATA.
          IF MASTER_IDOC_DATA-SEGNAM(1) EQ 'Z'.
            DELETE MASTER_IDOC_DATA.
          ENDIF.
        ENDLOOP.
    ENDIF.
ENDENHANCEMENT.
