"Name: \PR:RV13A906\FO:ENQUEUE\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_BLOCK_VK12.
*    DATA: V_KSCHL TYPE KSCHA.
*    IMPORT V_KSCHL FROM MEMORY ID 'VKS'.
    IF SY-TCODE EQ 'VK12'.
      IF RV13A-KSCHL EQ 'ZDES'
      OR RV13A-KSCHL EQ 'ZLPP'
      OR RV13A-KSCHL EQ 'ZDSS'
      OR RV13A-KSCHL EQ 'ZDPL'.
        DATA: V_CANCELA(13).
        DATA: V_MATNR TYPE MATNR.
        IMPORT F001 F002 F003 F004 SEL_DATE FROM MEMORY ID 'RV_COND_MEMORY_01'.
        IMPORT V_CANCELA FROM MEMORY ID 'M55TV@'.
*    IF V_CANCELA EQ 'CANCELACION'.
*      SET PARAMETER ID 'MAR' FIELD V_MATNR.
        READ TABLE F004 INDEX 1.
        IF SY-SUBRC EQ 0.
          MOVE F004-LOW TO E_KOMG-MATNR.
*      MOVE V_MATNR TO E_KOMG-MATNR.
        ENDIF.
        E_INDEX = 4.
*    ENDIF.
      ENDIF.
    ENDIF.
ENDENHANCEMENT.
