"Name: \PR:SAPMM06E\FO:PARAMETER_SETZEN\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_IDOC_PO_ZSB.

*    DATA: INT_EKPO LIKE EKPO OCCURS 0 WITH HEADER LINE.
*    DATA: V_CODE TYPE SY-TCODE.
*
*    CHECK SY-UCOMM EQ 'OPT1'
*    OR SY-UCOMM EQ 'MESAVE'.
*
*    IF EKKO-BSART EQ 'ZSB'.
*
*      WAIT UP TO 1 SECONDS.
*
*      SELECT * INTO TABLE INT_EKPO FROM EKPO
*      WHERE EBELN EQ EKKO-EBELN.
*      IF SY-SUBRC EQ 0.
*
*        V_CODE = SY-TCODE.
*
*        CALL FUNCTION 'ZCREATE_IDOC_ORDERS_ZSB'
*        EXPORTING
*          EBELN       = EKKO-EBELN
*          BSART       = EKKO-BSART
*          TCODE       = V_CODE
*        TABLES
*          IT_EKPO_ZSB = INT_EKPO.
*
*      ENDIF.
*    ENDIF.

ENDENHANCEMENT.
