"Name: \PR:SAPLWF03\FO:ITEM_CALCULATE_AS_CALL\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_NO_DISPLAY_BW_WINDOWS.
    DATA: CHECK.
    GET PARAMETER ID '%ZCHECK'  FIELD CHECK.
    IF SY-TCODE EQ 'ZASA'
    AND CHECK IS NOT INITIAL.
      G_T627-ASTFB = 'ZWSTR_ADD_QUOTAS_SAP_BW'.
    ENDIF.
ENDENHANCEMENT.
