"Name: \PR:SAPLMV01\FO:IDOC_ANLEGEN\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_CHANGE_EXTWG.

    DATA: V_EWBEZ TYPE EWBEZ.
    DATA: WA_MVKE TYPE MVKE.

    SELECT SINGLE * INTO WA_MVKE FROM MVKE WHERE MATNR = IHEADDATA-MATERIAL
                                             AND VKORG = 'OV10'
                                             AND VTWEG = 'C5'
                                             AND KTGRM = '01'.
    IF SY-SUBRC NE 0.
      EXIT.
    ENDIF.

    LOOP AT TCLIENTDATA.
      SELECT SINGLE TWEWT~EWBEZ INTO V_EWBEZ FROM TWEWT WHERE SPRAS EQ 'S '
      AND EXTWG EQ TCLIENTDATA-EXTMATLGRP.
      IF SY-SUBRC EQ 0.
        MOVE V_EWBEZ TO TCLIENTDATA-EXTMATLGRP.
        MODIFY TCLIENTDATA.
      ENDIF.
    ENDLOOP.
ENDENHANCEMENT.
