"Name: \PR:SAPLWBB_HPR1\FO:IDOC_DATA_CREATE\SE:END\EI
ENHANCEMENT 0 ZENH_ADD_FIELD_WGLIF.


*    TABLES: EINA.
*    DATA: I_ZE1WBBPG   TYPE ZE1WBBPG,
*          I_IDOC_DATA  TYPE EDIDD_SHORT.
*
*    FIELD-SYMBOLS <FS_EINA> TYPE EINA.
*
*    I_IDOC_DATA-SEGNAM = 'ZE1WBBPG'.
*
*    SELECT SINGLE * FROM EINA WHERE MATNR EQ I_MARA_READ-MATNR.
*    IF SY-SUBRC EQ 0.
*      IF EINA-WGLIF IS NOT INITIAL.
*         I_ZE1WBBPG-WGLIF = EINA-WGLIF.
*         I_IDOC_DATA-SDATA = I_ZE1WBBPG.
*         APPEND I_IDOC_DATA TO IDOC-IDOC_DATA.
*         ADD 1 TO IDOC-SEG_COUNTER.
*      ENDIF.
*    ENDIF.


ENDENHANCEMENT.
