"Name: \FU:IDOC_ENGINE\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_DEL_MAT_CATMAN_PRECIO_ALL.
*---------------------------------
*DEPURACION DE MATERIALES PARA GK-
*---------------------------------
    DATA T_ART_FOR_ALL_OUT TYPE TABLE_ART_FOR_ALL.

    CALL FUNCTION 'ZMF_DEPURE_ARTICLES_TO_GK'
    EXPORTING
      T_ART_FOR_ALL           = T_ART_FOR_ALL
      T_SITES                 = T_SITES
    TABLES
      T_ART_FOR_ALL_OUT       = T_ART_FOR_ALL_OUT.

    T_ART_FOR_ALL[] = T_ART_FOR_ALL_OUT[].
ENDENHANCEMENT.
