"Name: \FU:CHANGEDOCUMENT_CLOSE\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_CHANGE_TABNAME_DLWK2.
    DATA: WA_CDPOS LIKE CDPOS.
    DATA: WA_WLK2 TYPE WLK2.
    LOOP AT INS_CDPOS INTO WA_CDPOS.
      IF WA_CDPOS-OBJECTCLAS EQ 'MAT_FULL'
      AND WA_CDPOS-TABNAME   EQ 'WLK2'
      AND WA_CDPOS-FNAME(1)  EQ 'Z'  .
        WA_CDPOS-TABNAME = 'DWLK2'.
        MOVE WA_CDPOS-TABKEY TO WA_WLK2.
        CLEAR WA_CDPOS-TABKEY.
        CONCATENATE WA_WLK2-vKORG WA_WLK2-VTWEG INTO WA_CDPOS-TABKEY.
        MODIFY INS_CDPOS FROM WA_CDPOS.
      ENDIF.
    ENDLOOP.
ENDENHANCEMENT.
