"Name: \PR:SAPLMV01\FO:KEY_TABELLEN_UEBERGEBEN_SMD\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_ONLY_MATNR_UMV_BD21.
    DATA: IT_MAW1 LIKE MAW1 OCCURS 0 WITH HEADER LINE.
    DATA: IT_MARA LIKE MARA OCCURS 0 WITH HEADER LINE.

    SELECT * INTO TABLE IT_MAW1
    FROM MAW1
    FOR ALL ENTRIES IN TMARMAKT
    WHERE MATNR EQ TMARMAKT-MATNR.

    SORT IT_MAW1 BY MATNR WVRKM.

    SELECT * INTO TABLE IT_MARA
    FROM MARA
    FOR ALL ENTRIES IN TMARMAKT
    WHERE MATNR EQ TMARMAKT-MATNR.

    SORT IT_MARA BY MEINS.

    LOOP AT TMARMAKT.
      READ TABLE IT_MAW1 WITH KEY MATNR = TMARMAKT-MATNR BINARY SEARCH.
      IF SY-SUBRC EQ 0.
        IF IT_MAW1-WVRKM IS NOT INITIAL.
          IF IT_MAW1-WVRKM NE TMARMAKT-MEINH.
            DELETE TMARMAKT.
            CONTINUE.
          ENDIF.
        ELSE.
          READ TABLE IT_MARA WITH KEY MATNR = TMARMAKT-MATNR BINARY SEARCH.
          IF IT_MARA-MEINS NE TMARMAKT-MEINH.
            DELETE TMARMAKT.
            CONTINUE.
          ENDIF.
        ENDIF.
      ELSE.
        READ TABLE IT_MARA WITH KEY MATNR = TMARMAKT-MATNR BINARY SEARCH.
        IF IT_MARA-MEINS NE TMARMAKT-MEINH.
          DELETE TMARMAKT.
          CONTINUE.
        ENDIF.
      ENDIF.
    ENDLOOP.
ENDENHANCEMENT.
