"Name: \PR:SAPLMGWA\FO:IDOC_MATERIAL_MAINTAINDATA_RT\SE:END\EI
ENHANCEMENT 0 ZENH_SEGMENTO_CANALESWEB.
    DATA: V_MATNR TYPE MATNR.
    DATA: WA_E1BPE1WLK2RT TYPE E1BPE1WLK2RT.
    DATA: WA_ZCANALESWEB TYPE ZCANALESWEB.
    DATA: WA_WLK2 TYPE WLK2.
    DATA: ZCANALESWEB LIKE ZCANALESWEB,
          T_ZCANALESWEB LIKE EDIDD
          OCCURS 0 WITH HEADER LINE.

    CLEAR T_ZCANALESWEB.
    REFRESH T_ZCANALESWEB.
    T_ZCANALESWEB-SEGNAM = 'ZCANALESWEB'.
BREAK jddtrejo.
    LOOP AT IDOC_DATA WHERE SEGNAM = 'E1BPE1WLK2RT'.
      MOVE IDOC_DATA-SDATA TO WA_E1BPE1WLK2RT.
      SELECT SINGLE * FROM WLK2 INTO WA_WLK2 WHERE MATNR EQ WA_E1BPE1WLK2RT-MATERIAL
      AND VKORG EQ WA_E1BPE1WLK2RT-SALES_ORG
      AND VTWEG EQ WA_E1BPE1WLK2RT-DISTR_CHAN
      AND WERKS EQ WA_E1BPE1WLK2RT-PLANT.
      IF SY-SUBRC EQ  0.
        MOVE-CORRESPONDING WA_E1BPE1WLK2RT TO ZCANALESWEB.
        MOVE-CORRESPONDING WA_WLK2 TO ZCANALESWEB.
        T_ZCANALESWEB-SDATA = ZCANALESWEB.
        APPEND T_ZCANALESWEB.
      ENDIF.
    ENDLOOP.

    LOOP AT T_ZCANALESWEB.
      IDX = SY-TABIX.
      APPEND T_ZCANALESWEB TO IDOC_DATA.
    ENDLOOP.


ENDENHANCEMENT.
