"Name: \FU:IDOC_INPUT_MBGMCR\SE:END\EI
ENHANCEMENT 0 ZENH_MOVIMIENTO_MERMA_MBGMCR.

    DATA: V_LIFEX TYPE TRAID,
          V_VBELN TYPE VBELN_VL,
          V_POSNR TYPE POSNR_VL,
          V_MSG(132) TYPE C,
          V_IDCAJA TYPE ZBULTO,
          WA_ZMM53_IDOC LIKE ZMM53_IDOC.

    IF  IDOC_STATUS-MSGTY EQ 'E'.

      IF IDOC_STATUS-MSGID NE 'ME'
      AND IDOC_STATUS-MSGNO NE '006'.
        DELETE FROM ZMM53_IDOC WHERE DOCNUM EQ IDOC_STATUS-DOCNUM.
        COMMIT WORK.
        EXIT.
      ENDIF.


      SPLIT E1BP2017_GM_HEAD_01-BILL_OF_LADING_LONG AT '/' INTO V_LIFEX V_VBELN V_POSNR.
      MOVE E1BP2017_GM_HEAD_01-BAR_CODE TO V_IDCAJA.

      CALL FUNCTION 'FORMAT_MESSAGE'
      EXPORTING
        ID              = IDOC_STATUS-MSGID
        LANG            = SY-LANGU
        NO              = IDOC_STATUS-MSGNO
        V1              = IDOC_STATUS-MSGV1
        V2              = IDOC_STATUS-MSGV2
        V3              = IDOC_STATUS-MSGV3
        V4              = IDOC_STATUS-MSGV4
      IMPORTING
        MSG             = V_MSG
      EXCEPTIONS
        NOT_FOUND       = 1.

      READ TABLE GOODSMVT_ITEM INDEX 1.

      UPDATE ZPEN_ENVIO SET MESSAGE = V_MSG
      LGORT   = GOODSMVT_ITEM-STGE_LOC
      WHERE LIFEX  EQ V_LIFEX
      AND VBELN  EQ V_VBELN
      AND POSNR  EQ V_POSNR
      AND EBELN  EQ E1BP2017_GM_ITEM_CREATE-PO_NUMBER
      AND EBELP  EQ E1BP2017_GM_ITEM_CREATE-PO_ITEM
      AND IDCAJA EQ V_IDCAJA
      AND MATNR  EQ E1BP2017_GM_ITEM_CREATE-MATERIAL
      AND WERKS  EQ E1BP2017_GM_ITEM_CREATE-PLANT.

      MOVE IDOC_STATUS-DOCNUM TO WA_ZMM53_IDOC-DOCNUM.
      MODIFY  ZMM53_IDOC FROM WA_ZMM53_IDOC.
      COMMIT WORK AND WAIT.
    ELSE.


      SPLIT E1BP2017_GM_HEAD_01-BILL_OF_LADING_LONG AT '/' INTO V_LIFEX V_VBELN V_POSNR.
      MOVE E1BP2017_GM_HEAD_01-BAR_CODE TO V_IDCAJA.

      READ TABLE GOODSMVT_ITEM INDEX 1.
      UPDATE ZPEN_ENVIO SET MESSAGE = SPACE
      LGORT   = GOODSMVT_ITEM-STGE_LOC
      WHERE LIFEX  EQ V_LIFEX
      AND VBELN  EQ V_VBELN
      AND POSNR  EQ V_POSNR
      AND EBELN  EQ E1BP2017_GM_ITEM_CREATE-PO_NUMBER
      AND EBELP  EQ E1BP2017_GM_ITEM_CREATE-PO_ITEM
      AND IDCAJA EQ V_IDCAJA
      AND MATNR  EQ E1BP2017_GM_ITEM_CREATE-MATERIAL
      AND WERKS  EQ E1BP2017_GM_ITEM_CREATE-PLANT.


*      DELETE FROM ZMM53_IDOC WHERE DOCNUM EQ IDOC_STATUS-DOCNUM.
*
*      COMMIT WORK AND WAIT.

    ENDIF.

ENDENHANCEMENT.
