"Name: \PR:SAPLVV01\EX:MASTERIDOC_CREATE_DEBMAS_06\EN:/SAPHT/DRM_LOTMGMT_SAPLVV01\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_DEBMAS_DELETE_OV01.
*      DATA: WA_E1KNNVM LIKE E1KNNVM.
*      DATA: WA_TABIX LIKE SY-TABIX.
*
*      LOOP AT T_IDOC_DATA.
*        IF T_IDOC_DATA-SEGNAM EQ 'E1KNNVM'.
*        WA_KNVV1M = T_IDOC_DATA-SDATA.
*        IF WA_KNVV1M-VKORG EQ 'OV01'.
*          V_TABIX = SY-TABIX + 1.
*          DELETE T_IDOC_DATA.
*          EXIT.
*        ENDIF.
*      ENDLOOP.
*
*      LOOP AT T_IDOC_DATA FROM V_TABIX.
*        IF T_IDOC_DATA-SEGNAM EQ 'E1KNNVM'.
*          EXIT.
*        ELSE.
*          DELETE T_IDOC_DATA.
*        ENDIF.
*      ENDLOOP.
ENDENHANCEMENT.
