"Name: \FU:MAP2E_MARM_TO_BAPIE1MARMRT\SE:END\EI
ENHANCEMENT 0 ZENH_FILL_EANTP_MARM.

DATA: V_HPEAN TYPE HPEAN.

SELECT SINGLE MEAN~HPEAN INTO V_HPEAN FROM MEAN WHERE MATNR EQ MARM-MATNR
                                                  AND EAN11 EQ MARM-EAN11.
MOVE V_HPEAN TO BAPIE1MARMRT-EWM_CW_UOM_TYPE.

ENDENHANCEMENT.
