"Name: \FU:LIPS_STATUS_MAINTAIN\SE:END\EI
ENHANCEMENT 0 ZENH_CHANGE_DATA_LIPS.

*    DATA: WA_LIPS LIKE LIPSVB.
*
*    IF SY-CPROG EQ 'ZGENERACION_ENTREGAS'.
*      LOOP AT FXLIPS INTO WA_LIPS.
*        MOVE '25' TO WA_LIPS-SITUA.
*        MODIFY FXLIPS  FROM WA_LIPS.
*      ENDLOOP.
*    ENDIF.


ENDENHANCEMENT.
