"Name: \PR:SAPLV69A\FO:USEREXIT_FIELD_MODIFICATION\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_DISABLE_CONDITION.
    IF SCREEN-NAME EQ 'KOMV-KBETR'.
      TABLES: KONV.
      SELECT SINGLE * FROM KONV WHERE KNUMV EQ KOMV-KNUMV
      AND KSCHL IN ('ZVK0', 'ZVK1' ).
      IF SY-SUBRC EQ 0.
        SCREEN-INPUT = 0.
      ENDIF.
    ENDIF.
ENDENHANCEMENT.
