"Name: \PR:SAPFMMEX\FO:PSTYP_KNTTP_NEU\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_EXCLUIR_VERIFICACION_IMUT.
  DATA: WA_MARA LIKE MARA.
    SELECT SINGLE * INTO WA_MARA FROM MARA WHERE MATNR EQ PSK_MATNR.
    IF WA_MARA-MTART EQ 'ZCIN'.
      EXIT.
    ENDIF.
ENDENHANCEMENT.
