"Name: \PR:SAPLWRF_ARTICLE_SCREENS\FO:T130F_LESEN_KOMPLETT\SE:END\EI
ENHANCEMENT 0 ZENH_AUTORIZA_DISMM.
** 10.02.2017 JPM VALIDA AUTORIZACION PARA PODER MODIFICAR CAMPO MARC-DISMM
*    LOOP AT SCREEN.
*      IF screen-name EQ 'MARC-DISMM'.
*          AUTHORITY-CHECK OBJECT 'ZDISMM'
*                 ID 'ACTVT' FIELD '02'
*                 ID 'WERKS' FIELD MARD-WERKS.
*          IF SY-SUBRC NE 0.
*            screen-input     = 0.
*            MODIFY SCREEN.
*          ENDIF..
*      ENDIF.
*    ENDLOOP.
ENDENHANCEMENT.
