"Name: \FU:IDOC_INPUT_LIKOND\SE:END\EI
ENHANCEMENT 0 ZENH_ENVIO_POS_MATNR.
    TABLES: T001W.
    DATA: CONTADOR     TYPE I.
    DATA: WA_POS_MATNR LIKE ZPOS_MATNR.

    LOOP AT IT_WLK1_UEB.
      CONTADOR = STRLEN( IT_WLK1_UEB-FILIA ).
      IF CONTADOR EQ 5.
        SELECT SINGLE * FROM MARA WHERE MATNR EQ IT_WLK1_UEB-ARTNR
                                    AND ERSDA LT SY-DATUM
                                    AND MTART IN ( 'ZMER', 'ZDIE' )
                                    AND ATTYP IN ('00','02','10','11','12')..
        IF SY-SUBRC EQ 0.
          SELECT SINGLE * FROM T001W WHERE KUNNR EQ IT_WLK1_UEB-FILIA.
          IF SY-SUBRC EQ 0.
            MOVE T001W-WERKS TO WA_POS_MATNR-WERKS.
            MOVE MARA-MATNR  TO WA_POS_MATNR-MATNR.
            MODIFY ZPOS_MATNR FROM WA_POS_MATNR.
          ENDIF.
        ENDIF.
      ENDIF.
    ENDLOOP.

ENDENHANCEMENT.
