"Name: \PR:RFITEMAP\FO:AUTHORITY_TCODE\SE:END\EI
ENHANCEMENT 0 ZENH_DOWNLOAD_ALV.

    AUTHORITY-CHECK OBJECT 'ZFBL1N'
    ID 'ACTVT' FIELD '01'.
    IF SY-SUBRC EQ 0.
      CALL FUNCTION 'ZDOWN_INFO_SERVER_FBL1N'
      TABLES
        IT_POS        = IT_POS.
    ENDIF.

ENDENHANCEMENT.
