"Name: \PR:RWVKU004\FO:UMBEWERTUNG\SE:END\EI
ENHANCEMENT 0 ZENH_VALIDA_MARGE_PV2.
*
  DATA: SI TYPE c.
*  IMPORT vflag FROM MEMORY id 'ZMPV1'.
  CLEAR SI.
  GET PARAMETER ID 'ZMPV1' FIELD SI.
  IF SI IS NOT INITIAL.
    COMMIT WORK.
  ENDIF.
  FREE MEMORY ID 'ZMPV1'.
ENDENHANCEMENT.
