"Name: \PR:SAPMF05A\FO:PAI_STORNOBELEG_ERZEUGEN\SE:BEGIN\EI
ENHANCEMENT 0 ZENH_CHECK_INVOICE.

    DATA: BEGIN OF WA_FACTURA,
      BUKRS   TYPE ZCFDITT_MXDI_XML-BUKRS,
      GJAHR   TYPE ZCFDITT_MXDI_XML-GJAHR,
      FACTURA TYPE ZCFDITT_MXDI_XML-FACTURA,
      ESTADO  TYPE ZCFDITT_MXDI_XML-ESTADO,
    END OF WA_FACTURA.

    SELECT SINGLE BUKRS GJAHR FACTURA ESTADO
    INTO WA_FACTURA
    FROM ZCFDITT_MXDI_XML
    WHERE BUKRS EQ BKPF-BUKRS
    AND GJAHR EQ RF05A-GJAHS
    AND FACTURA EQ RF05A-BELNS
    AND UUID NE SPACE. "JDDTS 31.10.2017 07:52 AM 5927

    IF SY-SUBRC EQ 0 AND SY-TCODE EQ 'FB08'.

      "JDDTS 23.11.2018 06:52 PM 6852 Inicio
      DATA: WA_ZTSD_CFDI_CANCEL TYPE ZTSD_CFDI_CANCEL.
      SELECT SINGLE *
        FROM ZTSD_CFDI_CANCEL INTO WA_ZTSD_CFDI_CANCEL
      WHERE FACTURA EQ RF05A-BELNS AND
            BUKRS   EQ BKPF-BUKRS  AND
            GJAHR   EQ RF05A-GJAHS AND
            ESTADO_CFDI EQ 'Cancelado'.
      "JDDTS 23.11.2018 06:52 PM 6852 Final

      IF SY-SUBRC NE 0.
       CALL FUNCTION 'FIN_UI_DECO_CUSTOMIZED_MESSAGE'
        EXPORTING
          i_arbgb = 'ZFI'
          i_dtype = 'E'
          i_msgnr = '044'.
*   &DOCUMENTO NO SE PUEDE ANULAR YA SE ENCUENTRA FACTURADO
      ENDIF.

    ENDIF.


ENDENHANCEMENT.
