"Name: \IC:ZPLPROTOP\EX:ZPLPROTOP_G4\EI
ENHANCEMENT 0 ZES_ZRWRPLPRO.
*INITIALIZATION.
DATA: MGV_MATNR_PROG LIKE RSVAR-REPORT,
      MGV_MATNR_SELOPT_TAB LIKE RSLDBDFS OCCURS 0 WITH HEADER LINE.
 FIELD-SYMBOLS <MGV_MATNR_SELOPT_CONV> TYPE STANDARD TABLE.

 MGV_MATNR_PROG = SY-REPID.
MGV_MATNR_SELOPT_TAB-NAME = 'ARTRNGE' .
APPEND MGV_MATNR_SELOPT_TAB.
CALL FUNCTION 'MGV_SELOP_AFTER_INITIALIZATION'
     EXPORTING
         PROGRAM        = MGV_MATNR_PROG
     TABLES
         SELOP          = MGV_MATNR_SELOPT_TAB
     EXCEPTIONS
         NO_PROGRAMNAME = 1
         OTHERS         = 2
          .

START-OF-SELECTION.
  LOOP AT MGV_MATNR_SELOPT_TAB.
    CONCATENATE MGV_MATNR_SELOPT_TAB-NAME'[]' INTO
    MGV_MATNR_SELOPT_TAB-NAME.
    ASSIGN (MGV_MATNR_SELOPT_TAB-NAME) TO <MGV_MATNR_SELOPT_CONV>.
    IF SY-SUBRC IS INITIAL.
      CALL FUNCTION 'MGV_SELOP_AFTER_START_OF_SEL'
           EXPORTING
                SELOPT_NAME = MGV_MATNR_SELOPT_TAB-NAME
           TABLES
                RANGE       = <MGV_MATNR_SELOPT_CONV>.
    ENDIF.
  ENDLOOP.
ENDENHANCEMENT.
