"Name: \PR:SAPMKCBR\FO:START\SE:BEGIN\EI
ENHANCEMENT 0 ZMMENH002_MERMAS.
data IT_ZMM_SPMERMAS type ZMM_SPMERMAS OCCURS  600 WITH HEADER LINE.
DATA RYEAR TYPE GJAHR.
DATA  G_W_SEL                TYPE CEDST.

   EXPORT sp TO MEMORY ID 'SP'. "CCV 23.06.2016
   break ccorona.

   LOOP AT sp .
     MOVE-CORRESPONDING SP TO IT_ZMM_SPMERMAS.
     IT_ZMM_SPMERMAS-WERKS = IT_ZMM_SPMERMAS-RPRCTR(4).
     READ TABLE G_T_SEL INTO G_W_SEL   WITH KEY FNAM = 'RYEAR'.
     IF SY-SUBRC EQ 0.
       MOVE G_W_SEL-LOW TO IT_ZMM_SPMERMAS-RYEAR.
     ENDIF.
    COLLECT IT_ZMM_SPMERMAS.
   ENDLOOP.

   IF IT_ZMM_SPMERMAS[] IS NOT INITIAL.
*     delete IT_ZMM_SPMERMAS where w001 is INITIAL and w002 is INITIAL.
     MODIFY ZMM_SPMERMAS FROM TABLE IT_ZMM_SPMERMAS.
     COMMIT WORK.
   ENDIF.


ENDENHANCEMENT.
