"Name: \PR:RWRF_MPA\FO:B3_INIT_STYLE\SE:END\EI
ENHANCEMENT 0 ZROUTINES_BLOCK3.
    LOOP AT GT_WORK_AREA_0200 INTO WA_WORK_AREA_0200.
      CALL FUNCTION 'ZMF_REVISION_CARGA_PERFIL'
      EXPORTING
        IN_RECORD        = WA_WORK_AREA_0200
      IMPORTING
        OUT_RECORD       = WA_WORK_AREA_0200.
      MODIFY GT_WORK_AREA_0200 FROM WA_WORK_AREA_0200.
    ENDLOOP.
ENDENHANCEMENT.
