"Name: \PR:RWWGENFB\FO:CREATE_DOCUMENTS\SE:BEGIN\EI
ENHANCEMENT 0 ZWAUF_OTB_FASHION_CLASSIC.

    DATA: ZWRFT_OTB_CHECK TYPE WRFT_OTB_CHECK.
    LOOP AT XAUPO.
      SELECT SINGLE * FROM T621 WHERE APSTP EQ  XAUPO-APSTP.
      IF SY-SUBRC EQ 0.
        SELECT SINGLE * INTO ZWRFT_OTB_CHECK FROM WRFT_OTB_CHECK WHERE BSART EQ T621-BSART.
        IF SY-SUBRC NE 0.
          P_POFASH = SPACE.
        ENDIF.
      ENDIF.
      EXIT.
    ENDLOOP.
ENDENHANCEMENT.
