"Name: \PR:RWVKP007\FO:START-OF-SELECTION\SE:BEGIN\EI
ENHANCEMENT 0 ZZ_VALIDATION_DATUM2.
"VALIDATION DATUM
  IF SY-TCODE EQ 'VKP5'.
    IF SY-DATUM > S_DATUM-LOW.
      MESSAGE 'Por favor, revise la fecha de inicio' TYPE 'S' DISPLAY LIKE 'E'.
      STOP.
    ENDIF.
  ENDIF.
ENDENHANCEMENT.
